### ISSUE TITLE
Ses dosyası oynatma talebi

### ISSUE THREAD

**Issue by ozgeekaratas** [Performans-Dev/hee_rsp_central-heating-control#48]
JIRA-1224665
Logoya basıldığında ekteki ses dosyasını oynatabilir miyiz?

**Comment by ilkerokutman** [comment]
buradan test edebilirsiniz.

**Comment by ozgeekaratas** [comment]
test tamam yayınlayabilrsiniz

**Comment by ilkerokutman** [comment]
production yayinina girmistir
